# These are supported funding model platforms

github: Azccriminal
patreon: Azccriminal
open_collective: Azccriminal
ko_fi: zamanhuseyinli
paypal: https://www.paypal.com/donate/?hosted_button_id=NKPHAU3NY3GZU
